// Emit portable SQL from data/seed.json so the EVRO database can be loaded into
// any PostgreSQL with a single command — no Node, no pg_dump:
//
//   createdb evro && psql -d evro -f evro/server/db/seed.sql
//
// Writes:
//   evro/server/db/schema.sql   ← DDL only (physical schema reference)
//   evro/server/db/seed.sql     ← DDL + TRUNCATE + INSERTs (whole database)
//
// Regenerate after editing the seed:  npm run sql   (in evro/server)
import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import crypto from 'node:crypto'
import { DDL, TABLES } from './migrate.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const SEED_PATH = path.resolve(__dirname, '../../data/seed.json')

const raw = await readFile(SEED_PATH, 'utf8')
const seed = JSON.parse(raw)
const hash = crypto.createHash('sha256').update(raw).digest('hex')

// SQL single-quote escape for a JSON payload (handles e.g. "Workers' Compensation").
const lit = (obj) => `'${JSON.stringify(obj).replace(/'/g, "''")}'`
const KEY = { savings_pct_config: 'group_id' } // others key on id

function inserts() {
  const out = []
  const tableFor = {
    krs: seed.krs, people: seed.people, sourcing_groups: seed.sourcing_groups,
    spend_categories: seed.spend_categories, savings_pct_config: seed.savings_pct_config,
    opportunities: seed.opportunities, initiatives: seed.initiatives, badges: seed.badges,
    points_ledger: seed.points_ledger,
  }
  for (const t of TABLES) {
    if (t === 'audit_log') continue
    const key = KEY[t] || 'id'
    for (const row of tableFor[t] || []) {
      out.push(`INSERT INTO ${t} (${key}, data) VALUES ('${String(row[key]).replace(/'/g, "''")}', ${lit(row)}::jsonb);`)
    }
  }
  for (const row of seed.audit_log || []) {
    out.push(`INSERT INTO audit_log (id, data, ts) VALUES ('${row.id}', ${lit(row)}::jsonb, '${row.ts}');`)
  }
  out.push(`INSERT INTO app_meta (key, value) VALUES ('meta', ${lit(seed.meta)}) ON CONFLICT (key) DO UPDATE SET value = excluded.value;`)
  out.push(`INSERT INTO app_meta (key, value) VALUES ('seed_hash', '${hash}') ON CONFLICT (key) DO UPDATE SET value = excluded.value;`)
  return out.join('\n')
}

const header = `-- Athens EVRO — PostgreSQL database (schema + seed)
-- AUTO-GENERATED from evro/data/seed.json by db/make-sql.mjs — do not edit by hand.
-- Load into any PostgreSQL:   createdb evro && psql -d evro -f seed.sql
`

const schemaSql = `-- Athens EVRO — schema (DDL only). AUTO-GENERATED by db/make-sql.mjs.\n${DDL.trim()}\n`
const seedSql = `${header}${DDL.trim()}

BEGIN;
TRUNCATE ${TABLES.join(', ')}, app_meta RESTART IDENTITY CASCADE;
${inserts()}
COMMIT;
`

await writeFile(path.resolve(__dirname, 'schema.sql'), schemaSql)
await writeFile(path.resolve(__dirname, 'seed.sql'), seedSql)
const rows = TABLES.reduce((a, t) => a + (t === 'audit_log' ? (seed.audit_log?.length || 0) : (seed[t]?.length || 0)), 0)
console.log(`schema.sql + seed.sql written · ${rows} rows · hash ${hash.slice(0, 12)}…`)
