-- Athens EVRO — schema (DDL only). AUTO-GENERATED by db/make-sql.mjs.
CREATE TABLE IF NOT EXISTS app_meta (key TEXT PRIMARY KEY, value TEXT);
CREATE TABLE IF NOT EXISTS krs               (id TEXT PRIMARY KEY, data JSONB);
CREATE TABLE IF NOT EXISTS people            (id TEXT PRIMARY KEY, data JSONB);
CREATE TABLE IF NOT EXISTS sourcing_groups   (id TEXT PRIMARY KEY, data JSONB);
CREATE TABLE IF NOT EXISTS spend_categories  (id TEXT PRIMARY KEY, data JSONB);
CREATE TABLE IF NOT EXISTS savings_pct_config(group_id TEXT PRIMARY KEY, data JSONB);
CREATE TABLE IF NOT EXISTS opportunities     (id TEXT PRIMARY KEY, data JSONB);
CREATE TABLE IF NOT EXISTS initiatives       (id TEXT PRIMARY KEY, data JSONB);
CREATE TABLE IF NOT EXISTS badges            (id TEXT PRIMARY KEY, data JSONB);
CREATE TABLE IF NOT EXISTS points_ledger     (id TEXT PRIMARY KEY, data JSONB);
CREATE TABLE IF NOT EXISTS audit_log         (id TEXT PRIMARY KEY, data JSONB, ts TIMESTAMPTZ);
CREATE INDEX IF NOT EXISTS idx_audit_ts ON audit_log (ts DESC);
